### ISSUE TITLE
它并不起作用

### ISSUE THREAD

**Issue by MYLF** [52cik/bilibili-haruna#4]
我将它克隆下来以后与其他models一起放在了live2d_models文件夹中，并且将项目提供的live2d-widget文件夹中的文件替换到了node_modules/live2d-widget/lib，当我hexo clean && hexo g以后，重新运行hexo s，界面中并没有出现live2d人物，live2d的配置文件我想是没有问题的，因为再次换回官方提供的models可以正常显示，那么问题来了，我该如何使本models生效？

**Comment by 52cik** [comment]
有可能是 live2d-widget 模块更新了，我抽空看看，现在还不能确定是什么问题。

**Comment by MYLF** [comment]
Okay

**Comment by 52cik** [comment]
1. 在你的 hexo 博客的 source 目录下创建 live2d_models 目录
2. 将本仓库中的 assets/haruna 复制到刚才创建的 live2d_models 目录中
    然后完整路径就是这样的 source/live2d_models/haruna
3. 安装 hexo-helper-live2d 模块
4. 在 _config.yml 中配置 live2d
```yml
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: ./live2d_models/haruna/22/model.2017.tomo-bukatsu.low.json
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7
```
这个配置是插件文档那复制黏贴过来的，我没改其他的，只改了其中的 model use 这个字段。
其中的 ./live2d_models/haruna/22/model.2017.tomo-bukatsu.low.json 就是你想要的模型完整路径。
需要想要哪个模型，自己换地址就好了。

祝你玩的愉快。
